# Generated by Django 2.1.5 on 2019-02-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190213_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='published_date',
            new_name='created_date',
        ),
    ]
