# Generated by Django 2.1.7 on 2019-03-19 03:03

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190315_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/thumbnail', verbose_name='대표이미지'),
        ),
    ]
