# Generated by Django 2.1.7 on 2019-03-21 08:06

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190319_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/image', verbose_name='대표이미지'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/thumbnail'),
        ),
    ]
